within ThermoCam.Tests;

package GT_ORC_architectures
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
  extends Modelica.Icons.Package;
end GT_ORC_architectures;